### ISSUE TITLE
Open Beta v6.18 | Help testing and hardening the next release

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2211]
RC version | v6.18.13
---------- | -------
Changelog | https://github.com/Fourdee/DietPi/blob/beta/CHANGELOG.txt
Code changes | https://github.com/Fourdee/DietPi/compare/master...beta
How to apply | https://github.com/Fourdee/DietPi/blob/beta/BRANCH_SYSTEM.md
v6.18.13 | https://github.com/Fourdee/DietPi/pull/2290

#### DietPi functionality
- DietPi-Globals | G_* functions are not available via `sudo`: https://github.com/Fourdee/DietPi/issues/2135
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection: https://github.com/Fourdee/DietPi/issues/2103
  - Current workaround is to disable the adapter that is not in use (not for internet connection).
- DietPi-Drive_Manager | encryptfs is currently not supported and will be removed from fstab, when executing drive manager: https://github.com/Fourdee/DietPi/issues/2078
#### DietPi visual
- DietPi-Globals | G_AG* functions show some wrong aligned output lines: https://github.com/Fourdee/DietPi/issues/1788
**€: Forwarded to Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913083**
- DietPi-Config | When bringing up WiFi interfaces with some WiFi adapters, a power management error is thrown. However this does not affect functionality: https://github.com/Fourdee/DietPi/issues/2198
#### SBC/device related
- RPi | LXAppearance (on LXDE desktop) hangs on dbus-launch: https://github.com/Fourdee/DietPi/issues/1791
- RPi | With OpenGL enabled, when switching to VC4HDMI soundcard selection becomes invalid: https://github.com/Fourdee/DietPi/issues/2173
- Pine A64 | Bluetooth add-on module currently not supported: https://github.com/Fourdee/DietPi/issues/528
- Odroid XU4 | Xorg (e.g. desktops) fail to start: https://github.com/Fourdee/DietPi/issues/2130
  - To use desktop, `/etc/X11/xorg.conf` needs to be removed.
  - But to use Kodi, `/etc/X11/xorg.conf` is required, so one will work, one will be broken.
- Odroid C2 | Kodi GPU acceleration does not work on Stretch images: https://github.com/Fourdee/DietPi/issues/1814
- Odroid C2 | HotSpot does not work with (some?) WiFi adapters: https://github.com/Fourdee/DietPi/issues/1955
- [x] <s>Odroid C1/2 | 3,5" LCD shield does not work via dietpi-config with current kernel: https://github.com/Fourdee/DietPi/issues/2256</s>
**€: Resolved for Beta 6.18.10 with: https://github.com/Fourdee/DietPi/pull/2265 + https://github.com/Fourdee/DietPi/commit/5c1e0f88e0c4183c5be4130cd8ce245304137da5**
- [x] <s>NanoPi Fire 3 | TTY1 does not work for HDMI output: https://github.com/Fourdee/DietPi/issues/2225
   - Current workaround is to switch to TTY2 after boot: `<CTRL>+<ALT>+<F2>`</s>
**€: Resolved with Beta v6.18.4: https://github.com/Fourdee/DietPi/pull/2230/commits/9aad8db62cde9efceb4ce16559a6b60ec853a554**
#### Software title related
- [x] <s>OpenBazaar | Client connection fails: https://github.com/Fourdee/DietPi/issues/1090</s>
**€: PR merged with Beta v6.18.4: https://github.com/Fourdee/DietPi/pull/2224**
- Node-RED | Pre-installed modules cannot be updated via webUI: https://github.com/Fourdee/DietPi/issues/2073
- Raspimjpeg | With Lighttpd, streaming mjpeg does not work: https://github.com/Fourdee/DietPi/issues/1747
- [x] <s>Kodi | Shutdown/Restart options are not available: https://github.com/Fourdee/DietPi/issues/2155</s>
**€: Resolved with v6.18.6: https://github.com/Fourdee/DietPi/commit/c173aac778b1eb11951fb8a39138adaca8d37500**
- [x] <s>Jackett | Reinstall creates additional nested install dir: https://github.com/Fourdee/DietPi/issues/2212</s>
**€: PR merged with Beta v6.18.3: https://github.com/Fourdee/DietPi/pull/2214**
- [x] <s>PHP/databases | When installing a database (MariaDB or SQLite) after PHP was already installed, the related PHP modules are not installed: https://github.com/Fourdee/DietPi/issues/2217#issuecomment-435599804</s>
**€: PR merged with Beta v6.18.3: https://github.com/Fourdee/DietPi/pull/2214**
- [x] ~Docker | Service start currently fails: https://github.com/Fourdee/DietPi/issues/2238~
  - Easy fix available within issue linked above.
**€: PR opened for Beta v6.18.7: https://github.com/Fourdee/DietPi/pull/2247**
- [x] ~Grafana | Global passwords with `;` or `#` inside are not applied correctly: https://github.com/Fourdee/DietPi/issues/2267~
**€: Resolved with Beta v6.18.10: https://github.com/Fourdee/DietPi/commit/3a607eb07bb25b9f8ae098775d81c4733597c6c6**
- [x] ~Tautulli | WebUI setup fails due to missing user permissions. Proper reinstall handling should be added add well: https://github.com/Fourdee/DietPi/issues/2273~
**PR merged with Beta v6.18.13: https://github.com/Fourdee/DietPi/pull/2274**

**Comment by Fourdee** [comment]
Beta testing now live for v6.18 release:
https://t.co/1fEdFPyBya

Will try and wrap up a few more tickets in the next few days.

**Comment by msdos** [comment]
I think this process of "open beta" could have a line in README.md, and an information about https://github.com/Fourdee/DietPi/blob/dev/BRANCH_SYSTEM.md#steps-to-use-the-dietpi-beta-branch for devs as well.

**Comment by MichaIng** [comment]
@msdos 
How exactly do you want to have it mentioned? Since everyone can freely switch to `beta` branch, it is obviously opened.
We could add an info that we will inform via GitHub, forum and Twitter about new "`Beta phases`", which means feature stop and bugfix concentration?

Note, that we introduced the beta branch just with the last release, so we are learning/testing how to use it best ourselves currently. Thinks might change about how we handle it until we found a way that suites best 😉.

But also for my impression we need to have `dev` and `beta` branch more separate. Keep beta branch untouched (so leave it match `master` branch) until open beta phase is started, so there is no doubt/question about beta phase being "opened"/"started" or not and users on beta branch will stay with current release until open beta has started. Also stay with feature stop then, to avoid implementing more testing cases and concentrate on fixing/stability. I hope we can increase trust into the beta program by this and win more users that are willing to stay with beta branch so it will grow to a real benefit.
@Fourdee 
What do you think?

**Comment by MichaIng** [comment]
Referenced Beta in forum: https://dietpi.com/phpbb/viewtopic.php?f=9&t=5254

**Comment by Fourdee** [comment]
@MichaIng 

> Keep beta branch untouched (so leave it match master branch) until open beta phase is started, so there is no doubt/question about beta phase being "opened"/"started" or not and users on beta branch will stay with current release until open beta has started. Also stay with feature stop then, to avoid implementing more testing cases and concentrate on fixing/stability. I hope we can increase trust into the beta program by this and win more users that are willing to stay with beta branch so it will grow to a real benefit.

Yep agree 👍 

I've been aiming to only push dev > beta, prior to "open beta (eg: when we twitter post)" when a significant change is made (eg: nextcloud install fix). Aside from that, yep, dev > beta branch should only be merged after our initial testing is passed, not before (which we do already).

**Comment by Fourdee** [comment]
Thanks to all Beta testers, v6.18 live, completed.

**Comment by MichaIng** [comment]
Released, will close 🎆 🍾
