### ISSUE TITLE
Open Beta v6.20 | Please help testing and hardening the upcoming release

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#2415]
RC version | v6.20.5
---------- | -------
Changelog | https://github.com/Fourdee/DietPi/blob/beta/CHANGELOG.txt
Code changes | https://github.com/Fourdee/DietPi/compare/master...beta
v6.20.1 => v6.20.2 | https://github.com/Fourdee/DietPi/pull/2432
v6.20.2 => v6.20.3 | https://github.com/Fourdee/DietPi/pull/2444
v6.20.3 => v6.20.4 | https://github.com/Fourdee/DietPi/pull/2455
v6.20.4 => v6.20.5 | https://github.com/Fourdee/DietPi/pull/2457
How to apply | https://github.com/Fourdee/DietPi/blob/beta/BRANCH_SYSTEM.md

### ToDo:
- [x] DietPi-Software | WireGuard: Add changelog entry and online docs
  - Print QR code to console to scan with mobile client: `qrencode -t ansiutf8 < /etc/wireguard/wg0-client.conf`
  - Client mode kill switch:
    ```
    PostUp = iptables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
    PreDown = iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
    ```
- [x] DietPi-Software | WireGuard: Fine tune install script, add optional client configs for only local network access, only server access or only DNS nameserver usage (Pi-hole combi). Do never overwrite existing configs on install.
- [x] DietPi-Software | WireGuard: Allow client setup install by skipping server config steps if user chosen by user.
- **EDIT: PR merged into `dev`: https://github.com/Fourdee/DietPi/pull/2420**

#### The following cases have been successfully tested by the devs, however it would be great if you could have a special eye on them when using the beta:
- DietPi-Software | WireGuard installation and setup: https://github.com/Fourdee/DietPi/issues/2052
- DietPi-Drive_Manager | Now allows to check & repair the /boot file system and you can trigger an automated fsck on next reboot for the root file system: https://github.com/Fourdee/DietPi/pull/2335
- DietPi-Software | SickRage has been replaced by Medusa: https://github.com/Fourdee/DietPi/pull/2369
- DietPi-Software | Nextcloud Talk: Minor install fix/enhancement and disable logging: https://github.com/Fourdee/DietPi/issues/2321
- DietPi-Software | SSH: Host-key generation on first boot has been optimized to automatically match current security standards: https://github.com/Fourdee/DietPi/issues/2375
- DietPi-Software | MPD: Updated installer to use "mpd" user, systemd unit hardening and reinstall/config handling enhancements: https://github.com/Fourdee/DietPi/pull/2381
- DietPi-Software | Samba: Logging has been moved to RAM: https://github.com/Fourdee/DietPi/issues/2396
- DietPi-Software | Grafana: Except on ARMv6, we now use the official APT repo, which includes updates of Grafana to new upstream versions (currently v5.4.3): https://github.com/Fourdee/DietPi/issues/2449
- DietPi-Software | Gitea: Updated to v1.7: https://github.com/Fourdee/DietPi/pull/2448
- DietPi-Config | RPi: Resolution > headless choice now disables video output and framebuffer completely via new undocumented config.txt entry: https://github.com/Fourdee/DietPi/issues/2401
- General | The order of our systemd boot scripts has been improved and hardened to prevent/fix potential issues: https://github.com/Fourdee/DietPi/pull/2357

#### DietPi functionality
- DietPi-Globals | G_* functions are not available via `sudo`: https://github.com/Fourdee/DietPi/issues/2135
- DietPi-Config | Enabling WiFi + Ethernet adapters, both on different subnets, breaks WiFi connection in some cases: https://github.com/Fourdee/DietPi/issues/2103
  - Current workaround is to disable the adapter that is not in use (not for internet connection).
  - Otherwise a custom routing table is required.
- DietPi-Drive_Manager | encryptfs is currently not supported and will be removed from fstab, when executing drive manager: https://github.com/Fourdee/DietPi/issues/2078

#### DietPi visual
- DietPi-Globals | G_AG* functions show some wrong aligned output lines: https://github.com/Fourdee/DietPi/issues/1788
  - Forwarded to Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913083
- [x] DietPi-Config | When bringing up WiFi interfaces with some WiFi adapters, a power management error is thrown. However this does not affect functionality: https://github.com/Fourdee/DietPi/issues/2198
**EDIT: Resolved with: https://github.com/Fourdee/DietPi/pull/2432/commits/17a1a064533630dbd4393f90f6f10de1c03cea7f, https://github.com/Fourdee/DietPi/commit/23c39c30cee52dffcf3a6d1ac84aa964b43603a5, https://github.com/Fourdee/DietPi/commit/48d584565062e30c10d9532266df03244aa02011**

#### SBC/device related
- RPi | LXAppearance (on LXDE desktop) hangs on dbus-launch: https://github.com/Fourdee/DietPi/issues/1791
- RPi | OpenGL/VC4 causes sound card selection to be invalid: https://github.com/Fourdee/DietPi/issues/2173
- Pine A64 | Bluetooth add-on module currently not supported: https://github.com/Fourdee/DietPi/issues/528
- Odroid C2 | HotSpot does not work with (some?) WiFi adapters: https://github.com/Fourdee/DietPi/issues/1955

#### Software title related
- Node-RED | Pre-installed modules cannot be updated via webUI: https://github.com/Fourdee/DietPi/issues/2073
- Raspimjpeg | With Lighttpd, streaming mjpeg does not work: https://github.com/Fourdee/DietPi/issues/1747
- [x] LXDE | Weather plugin fails to retrieve data and find new locations: https://github.com/Fourdee/DietPi/issues/2416
**EDIT: Resolved with: https://github.com/Fourdee/DietPi/commit/ad5a082d3eaabaec4ae37541f56ca620c312a8d8**

**Comment by MichaIng** [comment]
@Fourdee 
Niice, yesterday I was just again thinking about an issue pinning feature would be nice and today I found it. Is this new or was I just blind? 😄

**Comment by MichaIng** [comment]
Released UTC 21:55.

Thanks to all testers ❤️ 🎆. Will mark this topic as resolved 😃.
