### ISSUE TITLE
Iteration v7.2 (release plan)

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi#4374]
Note: This issue is create to make sure all the related systems are properly updates (docs, wiki, website, release notes, Twitter, Facebook etc.). The standard list of tasks associated with generating the release should be still maintained in [wiki](https://github.com/MichaIng/DietPi/wiki/Release-tasks).

## Preparation

* [x]  Review / update [`CHANGELOG.md`](https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt)

## Day 0
A new development cycle starts with a subversion increment, or major version increment when we drop support for an old Debian version or old DietPi versions. The RC version during the development cycle is "-1", to clearly identify unstable version strings, e.g. v7.1.x => v7.2.-1.

## First week
* [x] Make the iteration planning - a little list of important items that shall be addressed within this release: #4375
  * [x] The GitHub milestone + an open issue added to the milestone: https://github.com/MichaIng/DietPi/milestone/102
* [x] Share this on Twitter, Forum, GitHub, Petreon, etc. to inform about the plans and allow any user to give some feedback on it. 

## 3rd week - Beta phase (testing)
`2021.05.22`
* [x]  Make sure the [appropriate pull request](https://github.com/MichaIng/DietPi/pulls) is available for the [documentation](https://dietpi.com/docs/releases/) with all the necessary changes:
   * [x] new software titles: https://github.com/MichaIng/DietPi-Docs/issues/487
   * [x] new hardware: https://github.com/MichaIng/DietPi-Docs/issues/490
   * [x] configuration changes: https://github.com/MichaIng/DietPi-Docs/pull/478 https://github.com/MichaIng/DietPi-Docs/pull/483
   * [x] other doc changes
* [x] Launch the initial beta
  * [x] Advertise open beta testing on:
    * [x] GitHub: https://github.com/MichaIng/DietPi/issues/4409
    * [x] Forum: https://dietpi.com/phpbb/viewtopic.php?t=9048
    * [x] DietPi-Banner MOTD
    * [x] Website slider: https://github.com/MichaIng/DietPi-Website/pull/103
    * [x] Twitter: https://twitter.com/DietPi_/status/1396478661063290882
    * [x] Facebook group: https://www.facebook.com/groups/167403007229675
    * [x] Patreon
* [x]  Determine if one or more hotfix needs to be applied (so the minor version is incremented e.g. 7.2.1, 7.2.2) #4415 #4423

## 2 days before the release
`2021.05.27`
* [x] Have a release PR open on the main repo which needs to be linked from the changelog/release notes. #4422
* [x] Have the docs release PR ready and reviewed, with release notes and required changes merged into dev already. https://github.com/MichaIng/DietPi-Docs/pull/494
* [x] Have a PR on the website ready to advertise the new release via website slide and have the docs PRs all ready and reviewed. https://github.com/MichaIng/DietPi-Website/pull/111

## Release
`2021.05.29`
* [x] Make the release
* [x] Publish the release notes ([Docs](https://dietpi.com/docs/releases/))
* [x] Mention the release notes in [DietPi Forum](https://dietpi.com/phpbb/viewforum.php?f=10)
* [x] Publish the main banner on the website, announcing new version
* [x] Update the MOTD
* [x] Update the dietpi.com update server

## Release announcements
`2021.05.30`
* [x] Determine if a hotfix is needed
* [x] Publish on Twitter ([tweet](https://twitter.com/DietPi_/status/1399029247054909440))
* [x] Publish on Facebook ([DietPi group](https://www.facebook.com/groups/167403007229675))

## Prep for the _next_ release
* [x] Select issues for the new iteration in the new milestone (v7.3)
* [x] Create a new _release plan_
* [x] Create a new section in [wiki](https://github.com/MichaIng/DietPi/wiki/Iteration-plans) associated to v7.3

**Comment by fpetru** [comment]
@MichaIng - A draft release plan, with actions on which we could help - it's just the initial version and I'm sure it needs more updates.

**Comment by MichaIng** [comment]
Good idea to make this an actual issue with each release cycle. Shall we add deadlines/dates here as well (see my basecamp notes)?

**Comment by StephanStS** [comment]
Post in the Facebook DietPi group:
---
![grafik](https://user-images.githubusercontent.com/57687516/120121827-f179fb80-c1a5-11eb-906e-da9fdf1dec5b.png)
