### ISSUE TITLE
Iteration plan 7.2 (May 2021)

### ISSUE THREAD

**Issue by fpetru** [MichaIng/DietPi#4375]
This plan captures the initial planning of the work to be done in May 2021. The full list of items in progress or finished is included in the [milestone v7.2](https://github.com/MichaIng/DietPi/milestone/102).

## Planned schedule
- 2021-05-22 - Beta
- 2021-05-29 - Release version 7.2

#### Highlights

- [x] Support new single board computers (SBC) NanoPi R4S, NanoPi R1 and Pinebook Pro. #4343 #4394
- [x] Desktop autologin as _non-root_ user will be enhanced :octicons-arrow-right-16: It will work with all SBCs/GPUs and without the need to add the user to the video and/or render system group. #4390
- [x] The browser, installed together with desktops, can be chosen via preference systems. As a start, the already implemented Firefox and Chromium can be chosen, but further browsers may be added soon. #4314
- [x] Support for further public VPN and DDNS providers will be added to [**DietPi-VPN**](https://dietpi.com/docs/dietpi_tools/#dietpi-vpn) and [**DietPi-DDNS**](https://dietpi.com/docs/dietpi_tools/#dietpi-ddns). #4404 #4407
- [x] [**Bitwarden_RS**](https://dietpi.com/docs/software/cloud/#bitwarden_rs) has been arenamed to "_vaultwarden_" by its author, to avoid confusing and possible legal conflicts with the original Bitwarden software. DietPi will apply to this change and (force or allow to) migrate existing installs. It's not a big change, but relevant to all existent Bitwarden_RS users. #4334

#### Full list

- https://github.com/MichaIng/DietPi/milestone/102
- Changelog (finished items): https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt

The release will include more bugs fixes, and possibly more enhancements and features.  

### DietPi Website

- [ ] :butterfly: Create a new page with performance metrics https://github.com/MichaIng/DietPi-Website/pull/109

---
### Legend

Mark | Description
-- | --
:running_woman: | work in progress
:warning: | blocked task
:butterfly: | stretch goal for this iteration
:frog: | more investigation required
:point_up: | under discussion within the team
:black_large_square: | a large work item, larger than one iteration

**Comment by fpetru** [comment]
@MichaIng - initial iteration plan, linked to [wiki](https://github.com/MichaIng/DietPi/wiki/Iteration-plans)

**Comment by MichaIng** [comment]
Great. I'll add links to the issues/PRs of each task. Also there is a "Completed" item missing in the legend, isn't it?

**Comment by fpetru** [comment]
@MichaIng - My initial idea was to have the checkmark as the sign as completed. But, if you see a need, I could still I add it

**Comment by MichaIng** [comment]
Makes sense, so we remove the symbol when done 👍.
