### ISSUE TITLE
Iteration v7.3 (release plan)

### ISSUE THREAD

**Issue by MichaIng** [MichaIng/DietPi#4453]
Note: This issue is create to make sure all the related systems are properly updates (docs, wiki, website, release notes, Twitter, Facebook etc.). The standard list of tasks associated with generating the release should be still maintained in [wiki](https://github.com/MichaIng/DietPi/wiki/Release-tasks).

## Preparation

* [x]  Review / update [`CHANGELOG.md`](https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt)

## Day 0
- [x] A new development cycle starts with a subversion increment, or major version increment when we drop support for an old Debian version or old DietPi versions. The RC version during the development cycle is "-1", to clearly identify unstable version strings, e.g. v7.2.x => v7.3.-1. #4439

## First week
* [x] Make the iteration planning - a little list of important items that shall be addressed within this release: #4452
  * [x] The GitHub milestone + an open issue added to the milestone: https://github.com/MichaIng/DietPi/milestone/103
* [x] Share this on Twitter, Forum, GitHub, Petreon, etc. to inform about the plans and allow any user to give some feedback on it. 

## 3rd week - Beta phase (testing)
To be done until: `2021.06.19`
* [x]  Make sure the [appropriate pull request](https://github.com/MichaIng/DietPi/pulls) is available for the [documentation](https://dietpi.com/docs/releases/) with all the necessary changes:
   * [x] new software titles
       - https://github.com/MichaIng/DietPi-Docs/pull/518
       - https://github.com/MichaIng/DietPi-Docs/pull/517
       - https://github.com/MichaIng/DietPi-Docs/pull/515
       - https://github.com/MichaIng/DietPi-Docs/pull/510
       - https://github.com/MichaIng/DietPi-Docs/pull/521
   * [x] new hardware
   * [x] configuration changes
   * [x] other doc changes
* [x] Launch the initial beta
  * [x] Advertise open beta testing on:
    * [x] GitHub: https://github.com/MichaIng/DietPi/issues/4498
    * [x] Forum: https://dietpi.com/phpbb/viewtopic.php?t=9149
    * [x] DietPi-Banner MOTD
    * [x] Website slider: https://dietpi.com/
    * [x] Twitter: https://twitter.com/DietPi_/status/1406611029782577154
    * [x] Facebook group
* [x]  Determine if one or more hotfix needs to be applied (so the minor version is incremented e.g. 7.3.1, 7.3.2)

## 2 days before the release
To be done until: `2021.06.24`
* [x] Have a release PR open on the main repo which needs to be linked from the [changelog](https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt)/release notes.
* [x] Assure that [update server version](https://github.com/MichaIng/DietPi/dev/beta/.update/version) and [DietPi-Globals default version](https://github.com/MichaIng/DietPi/blob/dev/dietpi/func/dietpi-globals) match.
* [x] Have the docs release PR ready and reviewed, with release notes and required changes merged into dev already.
* [x] Have a PR on the website ready to advertise the new release via website slide and have the docs PRs all ready and reviewed.

## Release
To be done at: `2021.06.26`
* [x] Make the release
* [x] Publish the release notes ([Docs](https://dietpi.com/docs/releases/))
* [x] Mention the release notes in [DietPi Forum](https://dietpi.com/phpbb/viewforum.php?f=10)
* [x] Publish the main banner on the website, announcing new version
* [x] Update the MOTD
* [x] Update software list ([DietPi Wiki ](https://github.com/MichaIng/DietPi/wiki/DietPi-Software-list))

## Release announcements
To be done at: `2021.06.27`
* [x] Determine if a hotfix is needed
* [x] Publish on Twitter ([DietPi account](https://twitter.com/DietPi_))
* [x] Publish on Facebook ([DietPi group](https://www.facebook.com/groups/167403007229675))

## Prep for the _next_ release
* [x] Select issues for the new iteration in the new milestone (v7.4)
* [x] Create a new _release plan_ #4530
* [x] Create a new section in [wiki](https://github.com/MichaIng/DietPi/wiki/Iteration-plans) associated to v7.4
